#!/usr/bin/env bash
for disease in Tra:trachoma:trachoma ; do

    for triplet in \
        temp1:europe-west1-c:aa \
        temp2:europe-west1-c:ab \
        temp3:europe-west2-c:ac \
        temp4:europe-west2-c:ad \
        temp5:europe-west3-c:ae \
        temp6:europe-west3-c:af \
        temp7:europe-west4-c:ag \
        temp8:europe-west4-c:ah \
        temp9:europe-west6-c:ai \
        temp10:europe-west6-c:aj
    do

		machine=$( echo $triplet | cut -f 1 -d : )
		zone=$( echo $triplet | cut -f 2 -d : )
		chunk=$( echo $triplet | cut -f 3 -d : )

        SHORT=$( echo $disease | cut -f 1 -d : )
        FILENAME=$( echo $disease | cut -f 2 -d : )
        DISEASENAME=$( echo $disease | cut -f 3 -d : )

        ## FIXME by parameterising CLI: update these for each run
		RUN_IDENTIFIER="202502c-TRA-espen"
		RUN_IU_DIRECTORY="${DISEASENAME}-IUs-20250225-espen-cloud-fitted"
		RUN_IU_CHUNK_ROOT="${RUN_IU_DIRECTORY}"
		SOURCE_DATA_DATE="20250225"

		SOURCE_DIRECTORY="source-data-20250225-espen"

        CORES=31
		START_YEAR=2026

		IU_FILE="iu-disease-data/${RUN_IU_DIRECTORY}/${RUN_IU_CHUNK_ROOT}-${chunk}.csv"

		# check file exists
		if [[ ! -f ${IU_FILE} ]] ; then
			echo "ERROR: IU file ${IU_FILE} not found"
			exit 1
		fi

		# check it has header line
		if [[ -z $( ag "Group_name" ${IU_FILE} ) ]] ; then
			echo "-> addiing header line to ${IU_FILE}"
			gsed -i -e '1s;^;"Group_name","IU_ID","IU_ID2"\n;' ${IU_FILE}
		fi

		echo "${machine}:${zone}"
		echo
		echo "gcloud compute ssh ${machine} --zone=${zone} --project=artrabbit-clients-ntd"
		echo

		for scenario in 1 2 3a 3b ; do

            echo "nohup env FORCE_ADD_TO_EXISTING_RUN=y DONT_WRITE_DB_RECORD=y bash ./run-sch-sth-tra.bash -d ${SHORT} -i ${IU_FILE} -n 200 -c ${CORES} -N ${RUN_IDENTIFIER} -e igor@artrabbit.com -s ${scenario} -p ${SOURCE_DIRECTORY} -k ntd-disease-simulator-data -K ntd-endgame-result-data -o ${RUN_IDENTIFIER} -w $((52*10)) -Y ${START_YEAR} >/dev/null </dev/null &"

        done

        echo
		echo "------"
        echo

	done
    echo
    echo
done
