INSERT INTO iu_disease ( iu_id, disease_id ) VALUES ( ( SELECT id FROM iu WHERE code = 'RWA38115' ), ( SELECT id FROM disease WHERE short = 'Man' ) );
INSERT INTO iu_disease ( iu_id, disease_id ) VALUES ( ( SELECT id FROM iu WHERE code = 'RWA38117' ), ( SELECT id FROM disease WHERE short = 'Man' ) );
INSERT INTO iu_disease ( iu_id, disease_id ) VALUES ( ( SELECT id FROM iu WHERE code = 'RWA38119' ), ( SELECT id FROM disease WHERE short = 'Man' ) );
INSERT INTO iu_disease ( iu_id, disease_id ) VALUES ( ( SELECT id FROM iu WHERE code = 'RWA38120' ), ( SELECT id FROM disease WHERE short = 'Man' ) );
INSERT INTO iu_disease ( iu_id, disease_id ) VALUES ( ( SELECT id FROM iu WHERE code = 'RWA38123' ), ( SELECT id FROM disease WHERE short = 'Man' ) );
INSERT INTO iu_disease ( iu_id, disease_id ) VALUES ( ( SELECT id FROM iu WHERE code = 'RWA38125' ), ( SELECT id FROM disease WHERE short = 'Man' ) );
INSERT INTO iu_disease ( iu_id, disease_id ) VALUES ( ( SELECT id FROM iu WHERE code = 'RWA38131' ), ( SELECT id FROM disease WHERE short = 'Man' ) );
INSERT INTO iu_disease ( iu_id, disease_id ) VALUES ( ( SELECT id FROM iu WHERE code = 'RWA38133' ), ( SELECT id FROM disease WHERE short = 'Man' ) );
INSERT INTO iu_disease ( iu_id, disease_id ) VALUES ( ( SELECT id FROM iu WHERE code = 'RWA38137' ), ( SELECT id FROM disease WHERE short = 'Man' ) );
